#!/usr/bin/env bash
# a Bash script that Install nginx on your machine listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart