#!/usr/bin/env bash
# configures a brand new Ubuntu machine with Nginx
# The HTTP response from Nginx should contain a custom header
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server
sudo apt-get update

# install Nginx
sudo apt-get -y install nginx

# allow Nginx to work with Ubuntu firewall
sudo ufw allow 'Nginx HTTP'

# change permissions to allow us create files in this directory
sudo chmod -R 755 /var/www

#  create the index page
echo "Hello World!" > /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.zmi.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart