#!/usr/bin/env bash
# Install and configure HAProxy on my lb-01 server
# Configure HAProxy to send traffic to web-01 & web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  zeus-frontend
        bind *:80
        mode http
        default_backend zeus-backend
backend zeus-backend
        balance roundrobin
        server 357912-web-01 100.25.34.18:80 check
        server 357912-web-02 52.201.186.83:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart