#!/usr/bin/env bash
# debugging nginx port 80
# STEPS: 
# delete the existing /etc/nginx/sites-enabled/default and replace it with a copy of
# /etc/nginx/sites-available/default. You do that by creating a symbolic link. 
# NOTE: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart